using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace GodotFest.VisaLetter.Models;

public enum LetterLanguage
{
    English,
    German
}

public enum LetterOutputLanguage
{
    English,
    German,
    Both
}

public enum AttendeeRoleKind
{
    Attendee,
    Speaker,
    SponsorRepresentative
}

/// <summary>
/// Everything the operator types in. Company and event facts are not here — they are
/// fixed in <see cref="EventFacts"/> so they cannot be mistyped per letter.
/// </summary>
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]
public sealed class LetterData
{
    [Required(ErrorMessage = "Full name is required — it must match the passport exactly.")]
    public string FullName { get; set; } = string.Empty;

    [Required(ErrorMessage = "Date of birth is required.")]
    public DateOnly? DateOfBirth { get; set; }

    [Required(ErrorMessage = "Place and country of birth are required.")]
    public string PlaceOfBirth { get; set; } = string.Empty;

    [Required(ErrorMessage = "Nationality is required.")]
    public string Nationality { get; set; } = string.Empty;

    [Required(ErrorMessage = "Passport number is required.")]
    public string PassportNumber { get; set; } = string.Empty;

    [Required(ErrorMessage = "Passport issue date is required.")]
    public DateOnly? PassportIssueDate { get; set; }

    [Required(ErrorMessage = "Passport expiry date is required.")]
    public DateOnly? PassportExpiryDate { get; set; }

    [Required(ErrorMessage = "Residential address is required.")]
    public string HomeAddress { get; set; } = string.Empty;

    [Required(ErrorMessage = "Employer is required.")]
    public string Employer { get; set; } = string.Empty;

    [Required(ErrorMessage = "Job title is required.")]
    public string JobTitle { get; set; } = string.Empty;

    public AttendeeRoleKind Role { get; set; } = AttendeeRoleKind.Attendee;

    [Required(ErrorMessage = "Booking reference is required — check the ticket exists in Pretix first.")]
    public string TicketOrderId { get; set; } = string.Empty;

    public string AccommodationEn { get; set; } = "Hotel in Munich, booked by the invitee";

    public string AccommodationDe { get; set; } = "Hotel in München, durch die eingeladene Person gebucht";

    [Required(ErrorMessage = "The receiving embassy or consulate is required.")]
    public string MissionName { get; set; } = string.Empty;

    [Required(ErrorMessage = "The address of the embassy or consulate is required.")]
    public string MissionAddress { get; set; } = string.Empty;

    [Required(ErrorMessage = "Letter date is required.")]
    public DateOnly? LetterDate { get; set; } = DateOnly.FromDateTime(DateTime.Today);

    public LetterOutputLanguage Output { get; set; } = LetterOutputLanguage.English;

    /// <summary>
    /// Schengen rules require the passport to stay valid for at least three months beyond
    /// the intended departure date. Surfaced as a warning rather than a hard error, because
    /// the operator may be preparing the letter before the attendee renews their passport.
    /// </summary>
    [JsonIgnore]
    public bool PassportExpiresTooSoon =>
        PassportExpiryDate is { } expiry && expiry < EventFacts.PassportValidUntilAtLeast;

    [JsonIgnore]
    public string RoleEnglish => Role switch
    {
        AttendeeRoleKind.Speaker => "speaker",
        AttendeeRoleKind.SponsorRepresentative => "sponsor representative",
        _ => "conference attendee"
    };

    [JsonIgnore]
    public string RoleGerman => Role switch
    {
        AttendeeRoleKind.Speaker => "Referent/in",
        AttendeeRoleKind.SponsorRepresentative => "Sponsorenvertreter/in",
        _ => "Konferenzteilnehmer/in"
    };

    /// <summary>
    /// Matches the naming produced by Scripts\New-VisaInvitationLetter.ps1 so letters
    /// generated by either route sit together consistently. An attendee's review copy gets a
    /// -DRAFT suffix after the language marker, so the issued letter keeps the canonical name.
    /// </summary>
    public string FileBaseName(LetterLanguage language, LetterIssueState state = LetterIssueState.ForWetSignature)
    {
        var safe = new string(FullName.Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray());
        while (safe.Contains("--", StringComparison.Ordinal))
        {
            safe = safe.Replace("--", "-", StringComparison.Ordinal);
        }

        safe = safe.Trim('-');
        if (string.IsNullOrEmpty(safe))
        {
            safe = "Attendee";
        }

        var stamp = (LetterDate ?? DateOnly.FromDateTime(DateTime.Today)).ToString("yyyyMMdd");
        var suffix = language == LetterLanguage.German ? "-DE" : string.Empty;
        var draft = state == LetterIssueState.Draft ? "-DRAFT" : string.Empty;
        return $"Invitation-Letter-{safe}-{stamp}{suffix}{draft}";
    }

    /// <summary>The name of the request file the attendee emails to the office.</summary>
    public string RequestFileName()
    {
        var letterName = FileBaseName(LetterLanguage.English);
        return $"{letterName.Replace("Invitation-Letter-", "Invitation-Request-", StringComparison.Ordinal)}.json";
    }
}
