namespace GodotFest.VisaLetter.Models;

/// <summary>
/// How a rendered letter is being issued. The same <c>LetterComposer</c> output feeds all
/// three, so a draft, a print-and-wet-sign copy and a signed letter can never drift apart.
/// </summary>
public enum LetterIssueState
{
    /// <summary>
    /// A review copy generated by the attendee. Visibly marked as unsigned so it cannot be
    /// passed off as an issued letter.
    /// </summary>
    Draft,

    /// <summary>
    /// Issued by the office for printing, signing by hand and stamping. Several Schengen
    /// posts still ask for an original wet signature, so this path must always remain.
    /// </summary>
    ForWetSignature,

    /// <summary>Issued by the office with the signature image embedded in the document.</summary>
    Signed
}

/// <summary>
/// The issue state plus, when signing, the signature image. The image is supplied at runtime
/// from the operator's own disk — it is never part of the deployed site, because anything
/// under <c>wwwroot/</c> is downloadable by anyone.
/// </summary>
/// <param name="State">Which of the three letter variants to compose.</param>
/// <param name="SignaturePng">A <c>data:image/png;base64,…</c> URL, required when signing.</param>
public sealed record LetterIssue(LetterIssueState State, string? SignaturePng = null)
{
    public static readonly LetterIssue Draft = new(LetterIssueState.Draft);

    public static readonly LetterIssue WetSignature = new(LetterIssueState.ForWetSignature);

    public static LetterIssue Signed(string signaturePng) =>
        new(LetterIssueState.Signed, signaturePng);

    public bool IsSigned => State == LetterIssueState.Signed && !string.IsNullOrWhiteSpace(SignaturePng);
}
